# Generated by Django 4.1.6 on 2023-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('NEBULOSA', 'Estrela'), ('NEBULOSA', 'Galáxia'), ('NEBULOSA', 'Planeta')], default='', max_length=100),
        ),
    ]
